[workspace]
members = [
  "crates/guard-net/*",
  "crates/consensus",
  "crates/types",
  "crates/common",
  "crates/validation",
  "crates/order-pool",
  "crates/rpc/*",
  "crates/eth/",
  #"it-harness",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/SorellaLabs/stale-guard"
repository = "https://github.com/SorellaLabs/stale-guard"
exclude = [".github/"]


[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 15

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1
incremental = false


[workspace.dependencies]
# revm
revm = { git = "https://github.com/bluealloy/revm", rev = "1609e07c68048909ad1682c98cf2b9baa76310b5" }
revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "1609e07c68048909ad1682c98cf2b9baa76310b5" }

reth-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-interfaces = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-db = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-rlp = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b", features = [
  "alloc",
] }
reth-codecs = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-ecies = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-rpc-builder = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-blockchain-tree = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-beacon-consensus = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-metrics = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-payload-builder = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-tasks = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-network = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-network-api = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-rpc-types-compat = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }
reth-libmdbx = { git = "https://github.com/paradigmxyz/reth", rev = "a389a2b" }


# alloy

alloy-sol-types = { version = "0.4.2", features = ["json"] }
alloy-sol-macro = { version = "0.4.2", features = ["json"] }
alloy-rlp = { version = "0.3.3" }
alloy-rlp-derive = { version = "0.3.3" }
alloy-primitives = { version = "0.4.2", features = ["rlp"] }


hex-literal = "0.4.1"
ethers-core = { version = "2.0.10", default-features = false }
ethers-providers = { version = "2.0.10", features = ["ws"] }
ethers-signers = { version = "2.0.10", default-features = false }
ethers-middleware = { version = "2.0.10", default-features = false }

consensus = { path = "./crates/consensus/" }
guard-types = { path = "./crates/types/" }
common = { path = "./crates/common/" }
validation = { path = "./crates/validation/" }

# anvil = { git = "https://github.com/SorellaLabs/fastfoundry" }
# anvil-core = { git = "https://github.com/SorellaLabs/fastfoundry" }

## misc
bytes = "1.4"
bitflags = "2.3"
tracing = "0.1.0"
tracing-appender = "0.2"
thiserror = "1.0"
serde_json = "1.0.94"
serde = { version = "1.0", default-features = false }
rand = "0.8.5"
strum = "0.25"
rayon = "1.7"
itertools = "0.11"
parking_lot = "0.12"
metrics = "0.21.1"                                    # Needed for `metrics-macro` to resolve the crate using `::metrics` notation
anyhow = "1.0.75"
url = "2.4.1"
auto_impl = "1.1.0"

### proc-macros
proc-macro2 = "1.0"
quote = "1.0"

## tokio
tokio-stream = "0.1.11"
tokio = { version = "1.21", features = ["full"], default-features = false }
tokio-util = { version = "0.7.4", features = ["codec"] }

## async
async-trait = "0.1.68"
futures = "0.3.26"
pin-project = "1.0.12"
futures-util = "0.3.25"

## json
jsonrpsee = { version = "0.20" }
jsonrpsee-core = { version = "0.20" }
jsonrpsee-types = { version = "0.20" }


## crypto
secp256k1 = { version = "0.27.0", default-features = false, features = [
  "global-context",
  "rand-std",
  "recovery",
] }
enr = { version = "0.9", default-features = false, features = ["k256"] }

### misc-testing
proptest = "1.0"
proptest-derive = "0.4"
arbitrary = "1.1"
assert_matches = "1.5.0"
aquamarine = "0.3"

