[package]
name = "stale-guard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Stale Guard Sidecar implementation
"""

[package.metadata.cargo-udeps.ignore]
normal = [
  # Used for diagrams in docs
  "aquamarine",
]

[dependencies]
reth.workspace = true
guard-rpc.workspace = true
guard-types.workspace = true
order-pool.workspace = true



clap = "4.4.8"
eyre = "0.6.9"

[target.'cfg(not(windows))'.dependencies]
jemallocator = { version = "0.5.0", optional = true }
jemalloc-ctl = { version = "0.5.0", optional = true }


[features]
default = ["jemalloc"]
jemalloc = ["dep:jemallocator", "dep:jemalloc-ctl"]


[[bin]]
name = "stale-guard"
path = "src/main.rs"
