[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json.workspace = true
ethers-core.workspace = true
reth-primitives.workspace = true
serde.workspace = true
reth-codecs.workspace = true
reth-rlp.workspace = true
