[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
ethers-core.workspace = true
reth-primitives.workspace = true
serde.workspace = true
reth-codecs.workspace = true
reth-rlp.workspace = true
